project:
   type: website
  
website: 
  title: "this art is HARD."
  navbar:
    left:
      - href: index.qmd
        icon: house-heart
    right:
      - href: what-is-data-art.qmd
        text: What is Data Art?
      - href: about-project.qmd
        text: About the Project
      - href: about-us.qmd
        text: About Us
      - href: acknowledge.qmd
        text: Acknowledgements & Inspiration

format:
  html: 
    theme: 
      light: flatly
      dark: darkly
    
execute:
  freeze: auto